### ISSUE TITLE
`show-all` command increases all HOTP counters

### ISSUE THREAD

**Issue by Toreno96** [apptension/onetimepass#27]
As you can see on [this GIF](https://github.com/apptension/onetimepass/blob/272fbb4ed12a8657b2913599c32c99ce0c60ea69/docs/watch-show-all.gif) included in the README (!), the `show-all` command automatically increases all HOTP counters.
This automatic behavior makes sense when printing the single HOTP using `show`, but in this case, it basically breaks the functionality.

This is a **critical bug**.

EDIT:
Summary of the discussion: https://github.com/apptension/onetimepass/issues/27#issuecomment-999760403

**Comment by Toreno96** [comment]
I have a few alternative approaches in my mind, which I have yet to put on paper, but the important thing to note is that RFC 4226 mentions in [section 7.2](https://datatracker.ietf.org/doc/html/rfc4226#section-7.2) and [section 7.4](https://datatracker.ietf.org/doc/html/rfc4226#section-7.4) that the counter is incremented every time a new HOTP is requested by the user (AKA this should happen automatically in the client).

This ofc still doesn't make sense to do in the case of `show-all` command, but probably should be considered when coming up with the optimal solution.

**Comment by Toreno96** [comment]
Another thing worth noting is that I compared the behavior to the Google Authenticator, and it seems it increments the counter _before_ showing it to the user, e.g. after I've added the secret with the counter equal to `0`, as the first code I got the code for the counter equal to `1`.

**Comment by Toreno96** [comment]
Ok, so as promised in https://github.com/apptension/onetimepass/issues/27#issuecomment-991916029, I considered a few alternative approaches:

1. Automatically increment the counter for the `show` command, don't do that for the `show-all` command.

    **Cons**:
    - this would introduce inconsistency to the interface.
    - ⚠️  user will have to use the `show` command for the specific ALIAS after/before using `show-all` to actually make the latter functional. This can be counter-intuitive to the user (why does `show-all` require to run `show`-single... ?). 

1. Add `-i/-I, --increment/--no-increment` flag, which will control if the counter should be automatically incremented. The default for the `show` could be `-i` to make the behavior automated for the user.

    **Cons**:
    - This should be supported only by the `show` command, as it still does not make to increment all of the counters in the `show-all` command. 
    - Alternatively, we could require `-i ALIAS` for the `show-all`, but that would introduce inconsistency to the interface.
    - Again, if we don't require `-i ALIAS`, ⚠️  user will have to use the `show` command for the specific ALIAS after/before using `show-all` to actually make the latter functional.
    - We have to handle this for TOTP (either ignore it and explicitly document this is ignored for TOTP, or alternatively, show an error to the user when they use the option for TOTP). This is not a big deal implementation-wise, but I would prefer to avoid introducing options that are valid only in some cases as long as it's possible.
    
1. Never increment the counter neither in `show` nor `show-all`, instead add the `inc`/`increment`/etc command, which will exist for this specific reason. This also would be compatible only with the HOTP, not TOTP, but IMHO it's a better approach to make _commands_ that are compatible only w/ the specific OTP type, than _options_.

    **Cons**:
    - ⚠️  Based on the above-mentioned RFC https://github.com/apptension/onetimepass/issues/27#issuecomment-991916029 and behavior of Google Authenticator https://github.com/apptension/onetimepass/issues/27#issuecomment-991927053, it seems that incrementing the counter should be as semi-automated as it's possible. It makes sense: the counter is supposed to be incremented at the specific step of the request (_before_, not after it, which is another bug BTW), so if we move the responsibility of incrementing the counter to the user, this will be error-prone and not really user-friendly. This con is also partially true for the previous suggestions.
    
1. Remove the support for HOTP from the app.

    This is something I believe @khanek suggested. While this basically removes the issue (and probably some other ones which we're not yet aware of) and makes a lot of sense (I'm not aware of any popular service that uses HOTP instead of TOTP for 2FA), I would really prefer to leave the support for HOTP in the app. This is supposed to be an alternative for Google Authenticator w/ additional features, and Google Authenticator supports the HOTP, so I would like to not remove the features that are there.

1. Remove the HOTP from `show-all` command.

    I don't really have specific pros or cons here. This approach makes sense IMHO, but I'm not 100% sure this is the best one.

1. Remove the `show-all` command.

    I'm a big fan of this approach TBH. How often do you need to actually fetch all possible OTPs configured in your client while authenticating to some service? I'm aware this was inspired by Google Authenticator which does exactly that, lists all the OTPs you have, but it makes sense in their case: Google Authenticator is a GUI tool, and I couldn't imagine clicking through the millions of screens to get the OTP for the specific service; using Google Authenticator is already cumbersome enough.
    
     However, in the `onetimepass`, we already introduced ALIASes (the easy-to-remember, easy-to-type identifiers that the user comes up with), which are the base entity for the whole app, and which IMHO are as convenient to use, or maybe even more, as listing all the possible OTPs (e.g. `otp show aws` vs. `otp show-all` and then filtering the `aws` using eyes or `grep`).
     
     Maybe I'm biased, but this seems like the easiest solution implementation-wise, and basically removes the issue. Although we still should fix the counter in the `show` command to be incremented _before_ the OTP is actually shown, and we could optionally provide the `-i/-I` option for debugging and user convenience.

**Comment by khanek** [comment]
I would also be in favor of the last solution. In fact, all we would need is a list of aliases, but not OTP codes.

**Comment by Toreno96** [comment]
Thank you @khanek for the input! 🙏 
We already have the list of aliases (the `otp ls` command), so we only have to delete the `show-all` command.

So, to summarize:
1. We will remove the `show-all` command (and all the mentions of it in the docs etc).
1. We will fix the current invalid behavior, where the counter is incremented _after_ the HOTP is shown. I've created a separate issue for that: https://github.com/apptension/onetimepass/issues/39
1. For now, we will not implement `-i/-I, --increment/--no-increment` option, however, we will leave that as the potential enhancement in the future.
